targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      json_serializable:
        enabled: true
        generate_for:
          - lib/**.codegen.dart
        options:
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_field_map: false
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          # field_rename: snake
          generic_argument_factories: false
          ignore_unannotated: false
          include_if_null: true
      freezed:
        enabled: true
        generate_for:
          - lib/**.codegen.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
          generic_argument_factories: true
          copy_with: true
